---
:variables:
  COST_OF_PRINTER: 3000.0
  COST_OF_FILAMENT: 23.0
  COST_OF_KWH: 0.1608
  TAZ_LIFE_EXPECTANCY: 4000.0
  COST_OF_WORKER: 13.0
  TIME_PER_PART: 0.25
  TAZ_HEAT_UP_USAGE: 0.36
  TAZ_HEAT_UP_TIME: 0.25
  TAZ_STABLE_USAGE: 0.16

:calculations:
  total_printer: (@COST_OF_PRINTER / @TAZ_LIFE_EXPECTANCY) * (@time / 60.0)
  total_filament: (@COST_OF_FILAMENT / (1000 / @weight))
  total_worker: (@COST_OF_WORKER * @TIME_PER_PART)
  total_electrical: ((@TAZ_HEAT_UP_USAGE * @TAZ_HEAT_UP_TIME) + (@TAZ_STABLE_USAGE * ((@time / 60.0) - @TAZ_HEAT_UP_TIME))) * @COST_OF_KWH
  total: total_printer + total_filament + total_worker + total_electrical